### ISSUE TITLE
Arrow-Head on "owning" side

### ISSUE THREAD

**Issue by christoph-frick** [metosin/schema-viz#7]
Given, that the resulting diagrams look like class diagrams, the arrow heads should be on the side, that holds the "reference".  So either put the diamond on the arrow-tail or change the direction of the edge (and change the `rangdir=BT`).  E.g. `Order <>- OrderItem` - an order has many items.

**Comment by ikitommi** [comment]
Thanks! Should have double-checked, so many years from my last class diagrams.... Also, we could  differentiate the `has` & `owns` relations for referenced schemas & embedded ones.

**Comment by christoph-frick** [comment]
i am just a dabbler, but i assume, that for `Order <>- OrderItem` the `odiamond` shape would be correct.

**Comment by ikitommi** [comment]
Looking forward to a PR :)

**Comment by christoph-frick** [comment]
sorry, it ended up as #9 - I have not yet found a way to "recycle" a ticket for a PR

**Comment by ikitommi** [comment]
I think there there is no way to recycle things in Github. But thanks for the contribution!

**Comment by ikitommi** [comment]
now in `[metosin/schema-viz "0.1.1"]`
